akagi:
  security:
    # 开放无需认证的接口
    permit-all-uri:
      - "/v1/api/login"
    # 刷新token需要的的权限
    json-web-token-refresh-permit: "MY_APP_CUSTOM:REFRESH_TOKEN_PERMIT"
    token-store-strategy: redis
    authorize-service-class: org.siu.akagi.authorize.AuthorizeServiceWithSuperUser


server:
  port: 9876

# redis 配置
spring:
  redis:
    host: 0.0.0.0
    port: 6379
    timeout: 20000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
