akagi:
  security:
    # 开放无需认证的接口
    permit-all-uri:
      - "/v1/api/login"
    # 刷新token需要的的权限
    json-web-token-refresh-permit: "MY_APP_CUSTOM:REFRESH_TOKEN_PERMIT"
    token-store-strategy: local
    authorize-service-class: org.siu.akagi.authorize.AuthorizeServiceWithSuperUser


server:
  port: 9876